### ISSUE TITLE
Update the information in npm website

### ISSUE THREAD

**Issue by tjapro** [torifat/yarn-update#2]
Hello!!

Only a suggestion...
I went to the [npm website](https://www.npmjs.com/package/yarn-update) and have not got any information saying: "Please, don't use this tool."
A person that do not go to github page, will install this package.

Thanks :-)

**Comment by torifat** [comment]
Thanks. I have added a deprecation message.

<img width="613" alt="screen shot 2017-03-27 at 10 08 27 pm" src="https://cloud.githubusercontent.com/assets/208544/24353670/5744de68-133a-11e7-8b29-ef28a8cdecbb.png">

**Comment by c-vetter** [comment]
It would still be nice to have this information *before* installing. Also, in my case, the deprecation warning went by me...
Why not kill the npm package altogether, if updating is too much work?
